# Missing Value

Describe any patterns you discover in missing values.

Data Quality

The first step to explore the data is to analyze its missing pattern. We use visna graph from extracat package to visualize the missing pattern. It can be observed that the varibale "qzipwork" which decribes the Zipcode of the locations where the respondents work has the most missing value. Also the "qsafety"" variable group contains a large amount of missing values which will probably cause bias to our conclusion in analysis. We will just ignore these variables and focus on the rest.

The other variables have few or no missing value on which we can perform further exploratory analysis safely. Given the condition of our data, we will maily concentrate on these varibales:
1.dependent varibles:
travel_code 
description

2.socioeconomic variables:
gender
age
income

3.spatial varibles:
qzipcmb(Zipcode)
borough

4.certain group of variables related to our topics:
qnyc(years of living in New York City)
qchildren
qrent
gFREIGHT varible groups


5.weight:
allwt(the weight for each record, provided by the survey)

In the process of exploration and analysis, we will also recode variable according to the situation and needs in analysis. The varibales we focus on generally have very few missing values. So instead of replacing them with other values, we will just exclude them when conducting analysis and plotting.

```{r}
library(extracat)
visna(tidy_df,sort = "b")

```